# Use root/example as user/password credentials
version: '3.1'

services:

  flaskapp:
    build: .
    ports:
      - "5000:5000"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      USE_POSTGRES: "yes"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example